name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x travel_mate/gradlew
    - name: Build with Gradle for travel mate
      run: ./travel_mate/gradlew build
      
    - name: Grant execute permission for gradlew
      run: chmod +x adb_demo/gradlew
    - name: Build with Gradle for travel mate
      run: ./adb_demo/gradlew build
