name: Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-adb_demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./adb_demo
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build debug APK for adb_demo
        run: ./gradlew assembleDebug
      
      - name: Build release APK for adb_demo
        run: ./gradlew assembleRelease
      
      - name: Upload debug APK for adb_demo
        uses: actions/upload-artifact@v4
        with:
          name: adb_demo-debug
          path: adb_demo/build/outputs/apk/debug/app-debug.apk
      
      - name: Upload release APK for adb_demo
        uses: actions/upload-artifact@v4
        with:
          name: adb_demo-release-unsigned
          path: adb_demo/build/outputs/apk/release/app-release-unsigned.apk

  build-travel_mate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travel_mate
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build debug APK for travel_mate
        run: ./gradlew assembleDebug
      
      - name: Build release APK for travel_mate
        run: ./gradlew assembleRelease
      
      - name: Upload debug APK for travel_mate
        uses: actions/upload-artifact@v4
        with:
          name: travel_mate-debug
          path: travel_mate/build/outputs/apk/debug/app-debug.apk
      
      - name: Upload release APK for travel_mate
        uses: actions/upload-artifact@v4
        with:
          name: travel_mate-release-unsigned
          path: travel_mate/build/outputs/apk/release/app-release-unsigned.apk
