name: Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-app1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travel_mate
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build debug APK for travel_mate
        run: ./gradlew assembleDebug
      
      - name: Build release APK for travel_mate
        run: ./gradlew assembleRelease
      
      - name: Find and display APK paths
        run: |
          echo "Searching for APK files..."
          find . -type f -name "*.apk" | sort
      
      - name: Upload all APKs for travel_mate
        uses: actions/upload-artifact@v4
        with:
          name: travel_mate-apks
          path: |
            ./app/**/*.apk
            ./build/**/*.apk
            ./**/*.apk

  build-app2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app2
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build debug APK for app2
        run: ./gradlew assembleDebug
      
      - name: Build release APK for app2
        run: ./gradlew assembleRelease
      
      - name: Locate APKs
        id: locate-apks
        run: |
          echo "DEBUG_APK=$(find . -name "*debug*.apk" | head -n 1)" >> $GITHUB_OUTPUT
          echo "RELEASE_APK=$(find . -name "*release*.apk" | head -n 1)" >> $GITHUB_OUTPUT
      
      - name: Upload debug APK for app2
        uses: actions/upload-artifact@v4
        with:
          name: app2-debug
          path: ${{ steps.locate-apks.outputs.DEBUG_APK }}
      
      - name: Upload release APK for app2
        uses: actions/upload-artifact@v4
        with:
          name: app2-release
          path: ${{ steps.locate-apks.outputs.RELEASE_APK }}
